### ISSUE TITLE
Implement janice as alternative to evepraisal

### ISSUE THREAD

**Issue by karl-kaefer** [xyx0826/Priceall#10]
Janice offers faster responses, more accurate plex/skill injector pricing and "split" which is very valuable for indu evaluation.

Website: https://janice.e-351.com/
API: https://github.com/E-351/janice

Thanks for considering it!

**Comment by xyx0826** [comment]
Thanks for the suggestion!

I'm remaking the tool with Xbox Game Bar Widget to turn it into a real overlay. I'll remember to add it in.

**Comment by xyx0826** [comment]
So I've decided the best course of action is to revive the current version before moving on to Game Bar, considering the current Game Bar SDK doesn't support transparency yet. Plus, I don't know why but apparently people are running EVE on Windows 7 or even in virtual machines for multiboxing.

I have started to clean up this mess I left two years ago. 😄 You can see development progress in the dev branch. Janice support will be added. Some of my friends also suggested ceve-market.org and I'll likely count that in as well.

**Comment by karl-kaefer** [comment]
Awesome! Thanks for resuming this tool - I'm using it almost every day 🙌

**Comment by xyx0826** [comment]
Janice implemented, along with a big bunch of internal changes. Set your market and data source of choice in the settings and you're good to go.

In my experience Janice seems to be much slower than Evepraisal though. I had to increase the network timeout limit to prevent it from erroring out. Tell me if this isn't supposed to happen.

Oh and, there's a bunch of new features I'm looking to add in the future. Persistant appraisals, buy/sell switching, etc...

**Comment by xyx0826** [comment]
Just added support for Janice's new markets. :)
