### ISSUE TITLE
Background not transparent in build 1.5.11

### ISSUE THREAD

**Issue by karl-kaefer** [xyx0826/Priceall#12]
The new build has the default blue background visible and no option to make the background transparent as in previous builds.

Tested on Windows 10 1909 (latest patch version)

**Comment by xyx0826** [comment]
Have you tried scrolling on the widget (without Ctrl)? It seems to work for me on 2004.

**Comment by karl-kaefer** [comment]
Ahhh thanks! Scrolling works :) 👍

**Comment by xyx0826** [comment]
Gonna mark this one solved. Feel free to reopen if more issues arise 😄
