### ISSUE TITLE
[Enhancement] A couple more ideas

### ISSUE THREAD

**Issue by razaqq** [xyx0826/Priceall#2]
Hello,
first i need to say this tool is great already. Thanks for the work!

I have a couple more ideas which would improve it quite a bit imo.

- Default location is jita. Maybe allow to change to the other trade hubs like Amarr etc. Should be as easy as changing a header in the query.

- Add and option to show buy value aswell as sell value. Some items are market manipulated...

- Changing the default hotkey for running a query would be nice or even auto-trigger a query when clipboard text changes.

**Comment by xyx0826** [comment]
Thanks. Great ideas.

I'm afraid with automatic clipboard trigger the tool will send any random text people copy to the server. I don't know if this will create a spamming issue or not.

If this is an issue, I may have to do some basic text validation to only send eve-related stuff.

**Comment by xyx0826** [comment]
I got the go-ahead from Evepraisal's developer. Really appreciate his support.

I think I'll put this feature in, but implement some kind of "flag check" that asks people to turn it off when things go out of control.
